name: animated_fav_button
description: A Flutter package for creating animated favorite buttons with attractive visual effects like hearts, likes, and other reactions. Easy to use, highly customizable with smooth animations and splash effects.
version: 0.0.1
homepage: https://github.com/GioRey/animated_fav_button
repository: https://github.com/GioRey/animated_fav_button
issue_tracker: https://github.com/GioRey/animated_fav_button/issues
documentation: https://github.com/GioRey/animated_fav_button#readme

topics:
  - animation
  - button
  - favorite
  - flutter
  - widget

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/
